CREATE TABLE IF NOT EXISTS "user" (
 id uuid PRIMARY KEY, name text NOT NULL, email text NOT NULL UNIQUE, "emailVerified" boolean NOT NULL DEFAULT false,
 image text, "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS session (
 id uuid PRIMARY KEY, "expiresAt" timestamptz NOT NULL, token text NOT NULL UNIQUE,
 "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now(),
 "ipAddress" text, "userAgent" text, "userId" uuid NOT NULL REFERENCES "user" ON DELETE CASCADE
);
CREATE INDEX session_user_idx ON session("userId");
CREATE TABLE IF NOT EXISTS account (
 id uuid PRIMARY KEY, "accountId" text NOT NULL, "providerId" text NOT NULL, "userId" uuid NOT NULL REFERENCES "user" ON DELETE CASCADE,
 "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz,
 scope text, password text, "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now(), UNIQUE("providerId","accountId")
);
CREATE TABLE IF NOT EXISTS verification (
 id uuid PRIMARY KEY, identifier text NOT NULL, value text NOT NULL, "expiresAt" timestamptz NOT NULL,
 "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX verification_identifier_idx ON verification(identifier);
CREATE TYPE member_role AS ENUM ('OWNER','ADMIN','SOCIAL_MANAGER','CONTENT_CREATOR','CLIENT_REVIEWER','VIEWER');
CREATE TYPE post_status AS ENUM ('DRAFT','PENDING_APPROVAL','APPROVED','SCHEDULED','QUEUED','PUBLISHING','PUBLISHED','PARTIALLY_PUBLISHED','FAILED','CANCELLED');
CREATE TABLE organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, timezone text NOT NULL DEFAULT 'Europe/Budapest', retention_days integer NOT NULL DEFAULT 365 CHECK(retention_days >= 30), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE TABLE organization_members (organization_id uuid NOT NULL REFERENCES organizations ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES "user" ON DELETE CASCADE, role member_role NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(organization_id,user_id));
CREATE TABLE clients (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations ON DELETE CASCADE, name text NOT NULL CHECK(length(name) BETWEEN 1 AND 120), color text NOT NULL DEFAULT '#168568', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, UNIQUE(organization_id,id));
CREATE TABLE client_members (organization_id uuid NOT NULL, client_id uuid NOT NULL, user_id uuid NOT NULL, role member_role NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(organization_id,client_id,user_id), FOREIGN KEY(organization_id,client_id) REFERENCES clients(organization_id,id) ON DELETE CASCADE, FOREIGN KEY(organization_id,user_id) REFERENCES organization_members(organization_id,user_id) ON DELETE CASCADE);
CREATE TABLE social_accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL, client_id uuid NOT NULL, platform text NOT NULL CHECK(platform IN ('facebook','instagram','linkedin','tiktok','google')), name text NOT NULL, remote_id text NOT NULL, mode text NOT NULL CHECK(mode IN ('mock','ayrshare','direct')), status text NOT NULL DEFAULT 'CONNECTED', token_health text NOT NULL DEFAULT 'HEALTHY', capabilities jsonb NOT NULL DEFAULT '[]', avatar text, last_sync_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, UNIQUE(organization_id,client_id,id), FOREIGN KEY(organization_id,client_id) REFERENCES clients(organization_id,id) ON DELETE CASCADE);
CREATE UNIQUE INDEX social_accounts_remote_unique ON social_accounts(organization_id,client_id,platform,mode,remote_id) WHERE deleted_at IS NULL;
CREATE TABLE social_credentials (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL, client_id uuid NOT NULL, social_account_id uuid NOT NULL UNIQUE, encrypted_value text NOT NULL, expires_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(organization_id,client_id,social_account_id) REFERENCES social_accounts(organization_id,client_id,id) ON DELETE CASCADE);
CREATE TABLE brand_profiles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL, client_id uuid NOT NULL UNIQUE, profile jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(organization_id,client_id) REFERENCES clients(organization_id,id) ON DELETE CASCADE);
CREATE TABLE media_assets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL, client_id uuid NOT NULL, name text NOT NULL, object_key text NOT NULL UNIQUE, mime_type text NOT NULL, size_bytes bigint NOT NULL CHECK(size_bytes > 0), width integer, height integer, duration_seconds real, status text NOT NULL DEFAULT 'UPLOADING', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, UNIQUE(organization_id,client_id,id), FOREIGN KEY(organization_id,client_id) REFERENCES clients(organization_id,id) ON DELETE CASCADE);
CREATE TABLE posts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL, client_id uuid NOT NULL, author_id uuid REFERENCES "user" ON DELETE SET NULL, caption text NOT NULL DEFAULT '', link text, status post_status NOT NULL DEFAULT 'DRAFT', revision integer NOT NULL DEFAULT 1, scheduled_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, UNIQUE(organization_id,client_id,id), FOREIGN KEY(organization_id,client_id) REFERENCES clients(organization_id,id) ON DELETE CASCADE);
CREATE INDEX posts_calendar_idx ON posts(organization_id,client_id,scheduled_at) WHERE deleted_at IS NULL;
CREATE INDEX posts_status_idx ON posts(organization_id,client_id,status,created_at DESC);
CREATE TABLE post_targets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL, client_id uuid NOT NULL, post_id uuid NOT NULL, social_account_id uuid NOT NULL, caption text NOT NULL, media_ids uuid[] NOT NULL DEFAULT '{}', status post_status NOT NULL DEFAULT 'DRAFT', remote_id text, error_code text, published_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(post_id,social_account_id), UNIQUE(organization_id,client_id,id), FOREIGN KEY(organization_id,client_id,post_id) REFERENCES posts(organization_id,client_id,id) ON DELETE CASCADE, FOREIGN KEY(organization_id,client_id,social_account_id) REFERENCES social_accounts(organization_id,client_id,id));
CREATE TABLE post_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL, client_id uuid NOT NULL, post_id uuid NOT NULL, revision integer NOT NULL, snapshot jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(post_id,revision), FOREIGN KEY(organization_id,client_id,post_id) REFERENCES posts(organization_id,client_id,id) ON DELETE CASCADE);
CREATE TABLE approval_workflows (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL, client_id uuid NOT NULL, name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id,client_id,id), FOREIGN KEY(organization_id,client_id) REFERENCES clients(organization_id,id) ON DELETE CASCADE);
CREATE TABLE approval_steps (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL, client_id uuid NOT NULL, workflow_id uuid NOT NULL, position integer NOT NULL CHECK(position > 0), kind text NOT NULL CHECK(kind IN ('INTERNAL','EXTERNAL')), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(workflow_id,position), FOREIGN KEY(organization_id,client_id,workflow_id) REFERENCES approval_workflows(organization_id,client_id,id) ON DELETE CASCADE);
CREATE TABLE approval_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL, client_id uuid NOT NULL, post_id uuid NOT NULL, revision integer NOT NULL, token_hash text NOT NULL UNIQUE, expires_at timestamptz NOT NULL, status text NOT NULL DEFAULT 'PENDING', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id,client_id,id), FOREIGN KEY(organization_id,client_id,post_id) REFERENCES posts(organization_id,client_id,id) ON DELETE CASCADE);
CREATE TABLE approval_comments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL, client_id uuid NOT NULL, approval_request_id uuid NOT NULL, author text NOT NULL, body text NOT NULL CHECK(length(body) BETWEEN 1 AND 5000), created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(organization_id,client_id,approval_request_id) REFERENCES approval_requests(organization_id,client_id,id) ON DELETE CASCADE);
CREATE TABLE publish_jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL, client_id uuid NOT NULL, target_id uuid NOT NULL UNIQUE, run_at timestamptz NOT NULL, status text NOT NULL DEFAULT 'PENDING', attempts integer NOT NULL DEFAULT 0, idempotency_key uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE, last_error text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id,client_id,id), FOREIGN KEY(organization_id,client_id,target_id) REFERENCES post_targets(organization_id,client_id,id) ON DELETE CASCADE);
CREATE INDEX publish_jobs_due_idx ON publish_jobs(run_at) WHERE status IN ('PENDING','RETRY');
CREATE TABLE publish_attempts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL, client_id uuid NOT NULL, publish_job_id uuid NOT NULL, attempt integer NOT NULL, status text NOT NULL, error_code text, provider_request_id text, started_at timestamptz NOT NULL DEFAULT now(), finished_at timestamptz, FOREIGN KEY(organization_id,client_id,publish_job_id) REFERENCES publish_jobs(organization_id,client_id,id) ON DELETE CASCADE);
CREATE TABLE mock_receipts (idempotency_key uuid PRIMARY KEY, remote_id text NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE analytics_daily (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL, client_id uuid NOT NULL, social_account_id uuid NOT NULL, day date NOT NULL, provider text NOT NULL, raw jsonb NOT NULL, normalized jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(social_account_id,day), FOREIGN KEY(organization_id,client_id,social_account_id) REFERENCES social_accounts(organization_id,client_id,id) ON DELETE CASCADE);
CREATE TABLE post_metrics (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL, client_id uuid NOT NULL, target_id uuid NOT NULL, provider text NOT NULL, raw jsonb NOT NULL, normalized jsonb NOT NULL, captured_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(organization_id,client_id,target_id) REFERENCES post_targets(organization_id,client_id,id) ON DELETE CASCADE);
CREATE TABLE webhook_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL, client_id uuid NOT NULL, provider text NOT NULL, external_id text NOT NULL, payload jsonb NOT NULL, status text NOT NULL DEFAULT 'PENDING', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(provider,external_id), FOREIGN KEY(organization_id,client_id) REFERENCES clients(organization_id,id) ON DELETE CASCADE);
CREATE TABLE notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL, client_id uuid NOT NULL, message text NOT NULL, resource_id uuid, created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(organization_id,client_id) REFERENCES clients(organization_id,id) ON DELETE CASCADE);
CREATE TABLE audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations ON DELETE CASCADE, client_id uuid, actor_id uuid REFERENCES "user" ON DELETE SET NULL, action text NOT NULL, resource_id uuid, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(organization_id,client_id) REFERENCES clients(organization_id,id) ON DELETE CASCADE);
CREATE INDEX audit_logs_scope_idx ON audit_logs(organization_id,client_id,created_at DESC);
CREATE TABLE oauth_states (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL, client_id uuid NOT NULL, user_id uuid NOT NULL REFERENCES "user" ON DELETE CASCADE, provider text NOT NULL, state_hash text NOT NULL UNIQUE, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(organization_id,client_id) REFERENCES clients(organization_id,id) ON DELETE CASCADE);
